using Content.Shared.Localizations;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Info.PlaytimeStats;

[GenerateTypedNameReferences]
public sealed partial class PlaytimeStatsEntry : ContainerButton
{
    public TimeSpan Playtime { get; private set; }  // new TimeSpan property
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    public PlaytimeStatsEntry(string role, TimeSpan playtime, Color? textColor, JobPrototype? proto, StyleBox styleBox) //starlight edit
    {
        IoCManager.InjectDependencies(this); // inject dependencies starlight

        RobustXamlLoader.Load(this);

        RoleLabel.Text = role;
        //starlight start
        RoleLabel.FontColorOverride = textColor;
        //starlight end
        Playtime = playtime;  // store the TimeSpan value directly
        PlaytimeLabel.Text = ContentLocalizationManager.FormatPlaytime(playtime);  // convert to string for display
        BackgroundColorPanel.PanelOverride = styleBox;

        //starlight, load icon
        IconLabel.Stretch = TextureRect.StretchMode.KeepAspectCentered;
        if (proto != null)
        {
            var sprite = _entManager.System<SpriteSystem>();
            var iconProto = _prototypeManager.Index(proto.Icon);
            IconLabel.Texture = sprite.Frame0(iconProto.Icon);
        }
        else
        {
            IconLabel.Texture = null;
        }
    }

    public void UpdateShading(StyleBoxFlat styleBox)
    {
        BackgroundColorPanel.PanelOverride = styleBox;
    }
    public string? PlaytimeText => PlaytimeLabel.Text;

    public string? RoleText => RoleLabel.Text;
}
